:global:
  componentName: crossplane
  feature_goldenTests: true
  testMatrix:
    key: instance
    entries:
      - defaults
      - defaults-with-provider
      - openshift4
      - openshift4-with-provider

.github/workflows/test.yaml:
  makeTarget: test -e instance=${{ matrix.instance }}
  goldenTest_makeTarget: golden-diff -e instance=${{ matrix.instance }}
