:global:
  componentName: crossplane
  feature_goldenTests: true
  testMatrix:
    key: instance
    entries:
      - defaults
      - openshift4

docs/antora.yml:
  name: crossplane
  title: crossplane

.github/workflows/test.yaml:
  makeTarget: test -e instance=${{ matrix.instance }}
  goldenTest_makeTarget: golden-diff -e instance=${{ matrix.instance }}
